// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: detected_violations.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDetectedViolation = `-- name: CreateDetectedViolation :one
INSERT INTO detected_violations (
  photo_id,
  description,
  confidence_score,
  safety_code_id,
  status
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, photo_id, description, confidence_score, status, created_at, safety_code_id
`

type CreateDetectedViolationParams struct {
	PhotoID         pgtype.UUID     `json:"photo_id"`
	Description     string          `json:"description"`
	ConfidenceScore pgtype.Numeric  `json:"confidence_score"`
	SafetyCodeID    pgtype.UUID     `json:"safety_code_id"`
	Status          ViolationStatus `json:"status"`
}

func (q *Queries) CreateDetectedViolation(ctx context.Context, arg CreateDetectedViolationParams) (DetectedViolation, error) {
	row := q.db.QueryRow(ctx, createDetectedViolation,
		arg.PhotoID,
		arg.Description,
		arg.ConfidenceScore,
		arg.SafetyCodeID,
		arg.Status,
	)
	var i DetectedViolation
	err := row.Scan(
		&i.ID,
		&i.PhotoID,
		&i.Description,
		&i.ConfidenceScore,
		&i.Status,
		&i.CreatedAt,
		&i.SafetyCodeID,
	)
	return i, err
}

const deleteDetectedViolation = `-- name: DeleteDetectedViolation :exec
DELETE FROM detected_violations
WHERE id = $1
`

func (q *Queries) DeleteDetectedViolation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDetectedViolation, id)
	return err
}

const getDetectedViolation = `-- name: GetDetectedViolation :one
SELECT id, photo_id, description, confidence_score, status, created_at, safety_code_id FROM detected_violations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDetectedViolation(ctx context.Context, id pgtype.UUID) (DetectedViolation, error) {
	row := q.db.QueryRow(ctx, getDetectedViolation, id)
	var i DetectedViolation
	err := row.Scan(
		&i.ID,
		&i.PhotoID,
		&i.Description,
		&i.ConfidenceScore,
		&i.Status,
		&i.CreatedAt,
		&i.SafetyCodeID,
	)
	return i, err
}

const listDetectedViolations = `-- name: ListDetectedViolations :many
SELECT id, photo_id, description, confidence_score, status, created_at, safety_code_id FROM detected_violations
WHERE photo_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDetectedViolations(ctx context.Context, photoID pgtype.UUID) ([]DetectedViolation, error) {
	rows, err := q.db.Query(ctx, listDetectedViolations, photoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DetectedViolation{}
	for rows.Next() {
		var i DetectedViolation
		if err := rows.Scan(
			&i.ID,
			&i.PhotoID,
			&i.Description,
			&i.ConfidenceScore,
			&i.Status,
			&i.CreatedAt,
			&i.SafetyCodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDetectedViolationsByStatus = `-- name: ListDetectedViolationsByStatus :many
SELECT id, photo_id, description, confidence_score, status, created_at, safety_code_id FROM detected_violations
WHERE photo_id = $1 AND status = $2
ORDER BY created_at DESC
`

type ListDetectedViolationsByStatusParams struct {
	PhotoID pgtype.UUID     `json:"photo_id"`
	Status  ViolationStatus `json:"status"`
}

func (q *Queries) ListDetectedViolationsByStatus(ctx context.Context, arg ListDetectedViolationsByStatusParams) ([]DetectedViolation, error) {
	rows, err := q.db.Query(ctx, listDetectedViolationsByStatus, arg.PhotoID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DetectedViolation{}
	for rows.Next() {
		var i DetectedViolation
		if err := rows.Scan(
			&i.ID,
			&i.PhotoID,
			&i.Description,
			&i.ConfidenceScore,
			&i.Status,
			&i.CreatedAt,
			&i.SafetyCodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDetectedViolationSafetyCode = `-- name: UpdateDetectedViolationSafetyCode :one
UPDATE detected_violations
SET safety_code_id = $2
WHERE id = $1
RETURNING id, photo_id, description, confidence_score, status, created_at, safety_code_id
`

type UpdateDetectedViolationSafetyCodeParams struct {
	ID           pgtype.UUID `json:"id"`
	SafetyCodeID pgtype.UUID `json:"safety_code_id"`
}

func (q *Queries) UpdateDetectedViolationSafetyCode(ctx context.Context, arg UpdateDetectedViolationSafetyCodeParams) (DetectedViolation, error) {
	row := q.db.QueryRow(ctx, updateDetectedViolationSafetyCode, arg.ID, arg.SafetyCodeID)
	var i DetectedViolation
	err := row.Scan(
		&i.ID,
		&i.PhotoID,
		&i.Description,
		&i.ConfidenceScore,
		&i.Status,
		&i.CreatedAt,
		&i.SafetyCodeID,
	)
	return i, err
}

const updateDetectedViolationStatus = `-- name: UpdateDetectedViolationStatus :one
UPDATE detected_violations
SET status = $2
WHERE id = $1
RETURNING id, photo_id, description, confidence_score, status, created_at, safety_code_id
`

type UpdateDetectedViolationStatusParams struct {
	ID     pgtype.UUID     `json:"id"`
	Status ViolationStatus `json:"status"`
}

func (q *Queries) UpdateDetectedViolationStatus(ctx context.Context, arg UpdateDetectedViolationStatusParams) (DetectedViolation, error) {
	row := q.db.QueryRow(ctx, updateDetectedViolationStatus, arg.ID, arg.Status)
	var i DetectedViolation
	err := row.Scan(
		&i.ID,
		&i.PhotoID,
		&i.Description,
		&i.ConfidenceScore,
		&i.Status,
		&i.CreatedAt,
		&i.SafetyCodeID,
	)
	return i, err
}
