// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: detected_violations.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDetectedViolationsByInspection = `-- name: CountDetectedViolationsByInspection :one
SELECT COUNT(*) FROM detected_violations dv
JOIN photos p ON dv.photo_id = p.id
WHERE p.inspection_id = $1
`

func (q *Queries) CountDetectedViolationsByInspection(ctx context.Context, inspectionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDetectedViolationsByInspection, inspectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDetectedViolation = `-- name: CreateDetectedViolation :one
INSERT INTO detected_violations (
  photo_id,
  description,
  confidence_score,
  safety_code_id,
  status,
  severity,
  location
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, photo_id, description, confidence_score, status, created_at, safety_code_id, severity, location
`

type CreateDetectedViolationParams struct {
	PhotoID         pgtype.UUID       `json:"photo_id"`
	Description     string            `json:"description"`
	ConfidenceScore pgtype.Numeric    `json:"confidence_score"`
	SafetyCodeID    pgtype.UUID       `json:"safety_code_id"`
	Status          ViolationStatus   `json:"status"`
	Severity        ViolationSeverity `json:"severity"`
	Location        pgtype.Text       `json:"location"`
}

func (q *Queries) CreateDetectedViolation(ctx context.Context, arg CreateDetectedViolationParams) (DetectedViolation, error) {
	row := q.db.QueryRow(ctx, createDetectedViolation,
		arg.PhotoID,
		arg.Description,
		arg.ConfidenceScore,
		arg.SafetyCodeID,
		arg.Status,
		arg.Severity,
		arg.Location,
	)
	var i DetectedViolation
	err := row.Scan(
		&i.ID,
		&i.PhotoID,
		&i.Description,
		&i.ConfidenceScore,
		&i.Status,
		&i.CreatedAt,
		&i.SafetyCodeID,
		&i.Severity,
		&i.Location,
	)
	return i, err
}

const deleteDetectedViolation = `-- name: DeleteDetectedViolation :exec
DELETE FROM detected_violations
WHERE id = $1
`

func (q *Queries) DeleteDetectedViolation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDetectedViolation, id)
	return err
}

const deletePendingAndDismissedViolationsByPhoto = `-- name: DeletePendingAndDismissedViolationsByPhoto :exec
DELETE FROM detected_violations
WHERE photo_id = $1 AND status IN ('pending', 'dismissed')
`

func (q *Queries) DeletePendingAndDismissedViolationsByPhoto(ctx context.Context, photoID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingAndDismissedViolationsByPhoto, photoID)
	return err
}

const deletePendingViolationsByPhoto = `-- name: DeletePendingViolationsByPhoto :exec
DELETE FROM detected_violations
WHERE photo_id = $1 AND status = 'pending'
`

func (q *Queries) DeletePendingViolationsByPhoto(ctx context.Context, photoID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingViolationsByPhoto, photoID)
	return err
}

const getDetectedViolation = `-- name: GetDetectedViolation :one
SELECT id, photo_id, description, confidence_score, status, created_at, safety_code_id, severity, location FROM detected_violations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDetectedViolation(ctx context.Context, id pgtype.UUID) (DetectedViolation, error) {
	row := q.db.QueryRow(ctx, getDetectedViolation, id)
	var i DetectedViolation
	err := row.Scan(
		&i.ID,
		&i.PhotoID,
		&i.Description,
		&i.ConfidenceScore,
		&i.Status,
		&i.CreatedAt,
		&i.SafetyCodeID,
		&i.Severity,
		&i.Location,
	)
	return i, err
}

const getViolationCountByOrganizationAndDateRange = `-- name: GetViolationCountByOrganizationAndDateRange :one
SELECT COUNT(*) as count
FROM detected_violations dv
JOIN photos ph ON ph.id = dv.photo_id
JOIN inspections i ON i.id = ph.inspection_id
JOIN projects p ON p.id = i.project_id
WHERE p.organization_id = $1
  AND dv.created_at >= $2
  AND dv.created_at < $3
`

type GetViolationCountByOrganizationAndDateRangeParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2    pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) GetViolationCountByOrganizationAndDateRange(ctx context.Context, arg GetViolationCountByOrganizationAndDateRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, getViolationCountByOrganizationAndDateRange, arg.OrganizationID, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getViolationCountBySeverityAndOrganization = `-- name: GetViolationCountBySeverityAndOrganization :many
SELECT dv.severity, COUNT(*) as count
FROM detected_violations dv
JOIN photos ph ON ph.id = dv.photo_id
JOIN inspections i ON i.id = ph.inspection_id
JOIN projects p ON p.id = i.project_id
WHERE p.organization_id = $1
  AND dv.created_at >= $2
  AND dv.created_at < $3
  AND dv.status = 'confirmed'
GROUP BY dv.severity
`

type GetViolationCountBySeverityAndOrganizationParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2    pgtype.Timestamptz `json:"created_at_2"`
}

type GetViolationCountBySeverityAndOrganizationRow struct {
	Severity ViolationSeverity `json:"severity"`
	Count    int64             `json:"count"`
}

func (q *Queries) GetViolationCountBySeverityAndOrganization(ctx context.Context, arg GetViolationCountBySeverityAndOrganizationParams) ([]GetViolationCountBySeverityAndOrganizationRow, error) {
	rows, err := q.db.Query(ctx, getViolationCountBySeverityAndOrganization, arg.OrganizationID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetViolationCountBySeverityAndOrganizationRow{}
	for rows.Next() {
		var i GetViolationCountBySeverityAndOrganizationRow
		if err := rows.Scan(&i.Severity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDetectedViolations = `-- name: ListDetectedViolations :many
SELECT id, photo_id, description, confidence_score, status, created_at, safety_code_id, severity, location FROM detected_violations
WHERE photo_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDetectedViolations(ctx context.Context, photoID pgtype.UUID) ([]DetectedViolation, error) {
	rows, err := q.db.Query(ctx, listDetectedViolations, photoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DetectedViolation{}
	for rows.Next() {
		var i DetectedViolation
		if err := rows.Scan(
			&i.ID,
			&i.PhotoID,
			&i.Description,
			&i.ConfidenceScore,
			&i.Status,
			&i.CreatedAt,
			&i.SafetyCodeID,
			&i.Severity,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDetectedViolationsByInspection = `-- name: ListDetectedViolationsByInspection :many
SELECT dv.id, dv.photo_id, dv.description, dv.confidence_score, dv.status, dv.created_at, dv.safety_code_id, dv.severity, dv.location FROM detected_violations dv
JOIN photos p ON dv.photo_id = p.id
WHERE p.inspection_id = $1
ORDER BY dv.created_at DESC
`

func (q *Queries) ListDetectedViolationsByInspection(ctx context.Context, inspectionID pgtype.UUID) ([]DetectedViolation, error) {
	rows, err := q.db.Query(ctx, listDetectedViolationsByInspection, inspectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DetectedViolation{}
	for rows.Next() {
		var i DetectedViolation
		if err := rows.Scan(
			&i.ID,
			&i.PhotoID,
			&i.Description,
			&i.ConfidenceScore,
			&i.Status,
			&i.CreatedAt,
			&i.SafetyCodeID,
			&i.Severity,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDetectedViolationsByInspectionAndStatus = `-- name: ListDetectedViolationsByInspectionAndStatus :many
SELECT dv.id, dv.photo_id, dv.description, dv.confidence_score, dv.status, dv.created_at, dv.safety_code_id, dv.severity, dv.location FROM detected_violations dv
JOIN photos p ON dv.photo_id = p.id
WHERE p.inspection_id = $1 AND dv.status = $2
ORDER BY dv.created_at DESC
`

type ListDetectedViolationsByInspectionAndStatusParams struct {
	InspectionID pgtype.UUID     `json:"inspection_id"`
	Status       ViolationStatus `json:"status"`
}

func (q *Queries) ListDetectedViolationsByInspectionAndStatus(ctx context.Context, arg ListDetectedViolationsByInspectionAndStatusParams) ([]DetectedViolation, error) {
	rows, err := q.db.Query(ctx, listDetectedViolationsByInspectionAndStatus, arg.InspectionID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DetectedViolation{}
	for rows.Next() {
		var i DetectedViolation
		if err := rows.Scan(
			&i.ID,
			&i.PhotoID,
			&i.Description,
			&i.ConfidenceScore,
			&i.Status,
			&i.CreatedAt,
			&i.SafetyCodeID,
			&i.Severity,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDetectedViolationsByStatus = `-- name: ListDetectedViolationsByStatus :many
SELECT id, photo_id, description, confidence_score, status, created_at, safety_code_id, severity, location FROM detected_violations
WHERE photo_id = $1 AND status = $2
ORDER BY created_at DESC
`

type ListDetectedViolationsByStatusParams struct {
	PhotoID pgtype.UUID     `json:"photo_id"`
	Status  ViolationStatus `json:"status"`
}

func (q *Queries) ListDetectedViolationsByStatus(ctx context.Context, arg ListDetectedViolationsByStatusParams) ([]DetectedViolation, error) {
	rows, err := q.db.Query(ctx, listDetectedViolationsByStatus, arg.PhotoID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DetectedViolation{}
	for rows.Next() {
		var i DetectedViolation
		if err := rows.Scan(
			&i.ID,
			&i.PhotoID,
			&i.Description,
			&i.ConfidenceScore,
			&i.Status,
			&i.CreatedAt,
			&i.SafetyCodeID,
			&i.Severity,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDetectedViolationNotes = `-- name: UpdateDetectedViolationNotes :one
UPDATE detected_violations
SET
  status = COALESCE($2, status),
  description = COALESCE($3, description)
WHERE id = $1
RETURNING id, photo_id, description, confidence_score, status, created_at, safety_code_id, severity, location
`

type UpdateDetectedViolationNotesParams struct {
	ID          pgtype.UUID         `json:"id"`
	Status      NullViolationStatus `json:"status"`
	Description pgtype.Text         `json:"description"`
}

func (q *Queries) UpdateDetectedViolationNotes(ctx context.Context, arg UpdateDetectedViolationNotesParams) (DetectedViolation, error) {
	row := q.db.QueryRow(ctx, updateDetectedViolationNotes, arg.ID, arg.Status, arg.Description)
	var i DetectedViolation
	err := row.Scan(
		&i.ID,
		&i.PhotoID,
		&i.Description,
		&i.ConfidenceScore,
		&i.Status,
		&i.CreatedAt,
		&i.SafetyCodeID,
		&i.Severity,
		&i.Location,
	)
	return i, err
}

const updateDetectedViolationSafetyCode = `-- name: UpdateDetectedViolationSafetyCode :one
UPDATE detected_violations
SET safety_code_id = $2
WHERE id = $1
RETURNING id, photo_id, description, confidence_score, status, created_at, safety_code_id, severity, location
`

type UpdateDetectedViolationSafetyCodeParams struct {
	ID           pgtype.UUID `json:"id"`
	SafetyCodeID pgtype.UUID `json:"safety_code_id"`
}

func (q *Queries) UpdateDetectedViolationSafetyCode(ctx context.Context, arg UpdateDetectedViolationSafetyCodeParams) (DetectedViolation, error) {
	row := q.db.QueryRow(ctx, updateDetectedViolationSafetyCode, arg.ID, arg.SafetyCodeID)
	var i DetectedViolation
	err := row.Scan(
		&i.ID,
		&i.PhotoID,
		&i.Description,
		&i.ConfidenceScore,
		&i.Status,
		&i.CreatedAt,
		&i.SafetyCodeID,
		&i.Severity,
		&i.Location,
	)
	return i, err
}

const updateDetectedViolationStatus = `-- name: UpdateDetectedViolationStatus :one
UPDATE detected_violations
SET status = $2
WHERE id = $1
RETURNING id, photo_id, description, confidence_score, status, created_at, safety_code_id, severity, location
`

type UpdateDetectedViolationStatusParams struct {
	ID     pgtype.UUID     `json:"id"`
	Status ViolationStatus `json:"status"`
}

func (q *Queries) UpdateDetectedViolationStatus(ctx context.Context, arg UpdateDetectedViolationStatusParams) (DetectedViolation, error) {
	row := q.db.QueryRow(ctx, updateDetectedViolationStatus, arg.ID, arg.Status)
	var i DetectedViolation
	err := row.Scan(
		&i.ID,
		&i.PhotoID,
		&i.Description,
		&i.ConfidenceScore,
		&i.Status,
		&i.CreatedAt,
		&i.SafetyCodeID,
		&i.Severity,
		&i.Location,
	)
	return i, err
}
