// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inspections.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInspection = `-- name: CreateInspection :one
INSERT INTO inspections (
  project_id,
  inspector_id,
  status
) VALUES (
  $1, $2, $3
)
RETURNING id, project_id, inspector_id, status, created_at, updated_at
`

type CreateInspectionParams struct {
	ProjectID   pgtype.UUID      `json:"project_id"`
	InspectorID pgtype.UUID      `json:"inspector_id"`
	Status      InspectionStatus `json:"status"`
}

func (q *Queries) CreateInspection(ctx context.Context, arg CreateInspectionParams) (Inspection, error) {
	row := q.db.QueryRow(ctx, createInspection, arg.ProjectID, arg.InspectorID, arg.Status)
	var i Inspection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.InspectorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInspection = `-- name: DeleteInspection :exec
DELETE FROM inspections
WHERE id = $1
`

func (q *Queries) DeleteInspection(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInspection, id)
	return err
}

const getInspection = `-- name: GetInspection :one
SELECT id, project_id, inspector_id, status, created_at, updated_at FROM inspections
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInspection(ctx context.Context, id pgtype.UUID) (Inspection, error) {
	row := q.db.QueryRow(ctx, getInspection, id)
	var i Inspection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.InspectorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInspectionCountByOrganizationAndDateRange = `-- name: GetInspectionCountByOrganizationAndDateRange :one
SELECT COUNT(*) as count
FROM inspections i
JOIN projects p ON p.id = i.project_id
WHERE p.organization_id = $1
  AND i.created_at >= $2
  AND i.created_at < $3
`

type GetInspectionCountByOrganizationAndDateRangeParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2    pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) GetInspectionCountByOrganizationAndDateRange(ctx context.Context, arg GetInspectionCountByOrganizationAndDateRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, getInspectionCountByOrganizationAndDateRange, arg.OrganizationID, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRecentInspectionsByOrganization = `-- name: GetRecentInspectionsByOrganization :many
SELECT i.id, i.project_id, i.inspector_id, i.status, i.created_at, i.updated_at, p.name as project_name, p.organization_id
FROM inspections i
JOIN projects p ON p.id = i.project_id
WHERE p.organization_id = $1
ORDER BY i.created_at DESC
LIMIT $2
`

type GetRecentInspectionsByOrganizationParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Limit          int32       `json:"limit"`
}

type GetRecentInspectionsByOrganizationRow struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	InspectorID    pgtype.UUID        `json:"inspector_id"`
	Status         InspectionStatus   `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ProjectName    string             `json:"project_name"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
}

func (q *Queries) GetRecentInspectionsByOrganization(ctx context.Context, arg GetRecentInspectionsByOrganizationParams) ([]GetRecentInspectionsByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, getRecentInspectionsByOrganization, arg.OrganizationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentInspectionsByOrganizationRow{}
	for rows.Next() {
		var i GetRecentInspectionsByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.InspectorID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectName,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInspections = `-- name: ListInspections :many
SELECT id, project_id, inspector_id, status, created_at, updated_at FROM inspections
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListInspections(ctx context.Context, projectID pgtype.UUID) ([]Inspection, error) {
	rows, err := q.db.Query(ctx, listInspections, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inspection{}
	for rows.Next() {
		var i Inspection
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.InspectorID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInspectionsByInspector = `-- name: ListInspectionsByInspector :many
SELECT id, project_id, inspector_id, status, created_at, updated_at FROM inspections
WHERE inspector_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListInspectionsByInspector(ctx context.Context, inspectorID pgtype.UUID) ([]Inspection, error) {
	rows, err := q.db.Query(ctx, listInspectionsByInspector, inspectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inspection{}
	for rows.Next() {
		var i Inspection
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.InspectorID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInspectionsByStatus = `-- name: ListInspectionsByStatus :many
SELECT id, project_id, inspector_id, status, created_at, updated_at FROM inspections
WHERE project_id = $1 AND status = $2
ORDER BY created_at DESC
`

type ListInspectionsByStatusParams struct {
	ProjectID pgtype.UUID      `json:"project_id"`
	Status    InspectionStatus `json:"status"`
}

func (q *Queries) ListInspectionsByStatus(ctx context.Context, arg ListInspectionsByStatusParams) ([]Inspection, error) {
	rows, err := q.db.Query(ctx, listInspectionsByStatus, arg.ProjectID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inspection{}
	for rows.Next() {
		var i Inspection
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.InspectorID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInspectionStatus = `-- name: UpdateInspectionStatus :one
UPDATE inspections
SET
  status = $2,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, project_id, inspector_id, status, created_at, updated_at
`

type UpdateInspectionStatusParams struct {
	ID     pgtype.UUID      `json:"id"`
	Status InspectionStatus `json:"status"`
}

func (q *Queries) UpdateInspectionStatus(ctx context.Context, arg UpdateInspectionStatusParams) (Inspection, error) {
	row := q.db.QueryRow(ctx, updateInspectionStatus, arg.ID, arg.Status)
	var i Inspection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.InspectorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
