// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type InspectionStatus string

const (
	InspectionStatusDraft      InspectionStatus = "draft"
	InspectionStatusInProgress InspectionStatus = "in_progress"
	InspectionStatusCompleted  InspectionStatus = "completed"
)

func (e *InspectionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InspectionStatus(s)
	case string:
		*e = InspectionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InspectionStatus: %T", src)
	}
	return nil
}

type NullInspectionStatus struct {
	InspectionStatus InspectionStatus `json:"inspection_status"`
	Valid            bool             `json:"valid"` // Valid is true if InspectionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInspectionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InspectionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InspectionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInspectionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InspectionStatus), nil
}

type OrganizationRole string

const (
	OrganizationRoleOwner  OrganizationRole = "owner"
	OrganizationRoleAdmin  OrganizationRole = "admin"
	OrganizationRoleMember OrganizationRole = "member"
)

func (e *OrganizationRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrganizationRole(s)
	case string:
		*e = OrganizationRole(s)
	default:
		return fmt.Errorf("unsupported scan type for OrganizationRole: %T", src)
	}
	return nil
}

type NullOrganizationRole struct {
	OrganizationRole OrganizationRole `json:"organization_role"`
	Valid            bool             `json:"valid"` // Valid is true if OrganizationRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrganizationRole) Scan(value interface{}) error {
	if value == nil {
		ns.OrganizationRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrganizationRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrganizationRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrganizationRole), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
	UserStatusDeleted   UserStatus = "deleted"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type ViolationSeverity string

const (
	ViolationSeverityCritical ViolationSeverity = "critical"
	ViolationSeverityHigh     ViolationSeverity = "high"
	ViolationSeverityMedium   ViolationSeverity = "medium"
	ViolationSeverityLow      ViolationSeverity = "low"
)

func (e *ViolationSeverity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ViolationSeverity(s)
	case string:
		*e = ViolationSeverity(s)
	default:
		return fmt.Errorf("unsupported scan type for ViolationSeverity: %T", src)
	}
	return nil
}

type NullViolationSeverity struct {
	ViolationSeverity ViolationSeverity `json:"violation_severity"`
	Valid             bool              `json:"valid"` // Valid is true if ViolationSeverity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullViolationSeverity) Scan(value interface{}) error {
	if value == nil {
		ns.ViolationSeverity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ViolationSeverity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullViolationSeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ViolationSeverity), nil
}

type ViolationStatus string

const (
	ViolationStatusPending   ViolationStatus = "pending"
	ViolationStatusConfirmed ViolationStatus = "confirmed"
	ViolationStatusDismissed ViolationStatus = "dismissed"
)

func (e *ViolationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ViolationStatus(s)
	case string:
		*e = ViolationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ViolationStatus: %T", src)
	}
	return nil
}

type NullViolationStatus struct {
	ViolationStatus ViolationStatus `json:"violation_status"`
	Valid           bool            `json:"valid"` // Valid is true if ViolationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullViolationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ViolationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ViolationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullViolationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ViolationStatus), nil
}

type DetectedViolation struct {
	ID              pgtype.UUID        `json:"id"`
	PhotoID         pgtype.UUID        `json:"photo_id"`
	Description     string             `json:"description"`
	ConfidenceScore pgtype.Numeric     `json:"confidence_score"`
	Status          ViolationStatus    `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	SafetyCodeID    pgtype.UUID        `json:"safety_code_id"`
	Severity        ViolationSeverity  `json:"severity"`
	Location        pgtype.Text        `json:"location"`
}

type Inspection struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	InspectorID pgtype.UUID        `json:"inspector_id"`
	Status      InspectionStatus   `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Job struct {
	ID             pgtype.UUID        `json:"id"`
	QueueName      string             `json:"queue_name"`
	JobType        string             `json:"job_type"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	Priority       int32              `json:"priority"`
	MaxAttempts    int32              `json:"max_attempts"`
	AttemptCount   int32              `json:"attempt_count"`
	ScheduledAt    pgtype.Timestamptz `json:"scheduled_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	Result         []byte             `json:"result"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	WorkerID       pgtype.Text        `json:"worker_id"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationMember struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Role           OrganizationRole   `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type OrganizationRateLimit struct {
	OrganizationID      pgtype.UUID        `json:"organization_id"`
	QueueName           string             `json:"queue_name"`
	Tier                string             `json:"tier"`
	MaxJobsPerHour      int32              `json:"max_jobs_per_hour"`
	MaxConcurrentJobs   int32              `json:"max_concurrent_jobs"`
	JobsInCurrentWindow int32              `json:"jobs_in_current_window"`
	WindowStart         pgtype.Timestamptz `json:"window_start"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Photo struct {
	ID           pgtype.UUID        `json:"id"`
	InspectionID pgtype.UUID        `json:"inspection_id"`
	StorageUrl   string             `json:"storage_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
}

type Project struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Name           string             `json:"name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Description    pgtype.Text        `json:"description"`
	ProjectType    pgtype.Text        `json:"project_type"`
	Status         pgtype.Text        `json:"status"`
	Address        pgtype.Text        `json:"address"`
	City           pgtype.Text        `json:"city"`
	State          pgtype.Text        `json:"state"`
	ZipCode        pgtype.Text        `json:"zip_code"`
	Country        pgtype.Text        `json:"country"`
}

type Report struct {
	ID           pgtype.UUID        `json:"id"`
	InspectionID pgtype.UUID        `json:"inspection_id"`
	StorageUrl   string             `json:"storage_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type SafetyCode struct {
	ID            pgtype.UUID        `json:"id"`
	Code          string             `json:"code"`
	Description   string             `json:"description"`
	Country       pgtype.Text        `json:"country"`
	StateProvince pgtype.Text        `json:"state_province"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        int32              `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                  pgtype.UUID        `json:"id"`
	Email               string             `json:"email"`
	Username            string             `json:"username"`
	PasswordHash        string             `json:"password_hash"`
	FirstName           pgtype.Text        `json:"first_name"`
	LastName            pgtype.Text        `json:"last_name"`
	Status              UserStatus         `json:"status"`
	StatusReason        pgtype.Text        `json:"status_reason"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	VerifiedAt          pgtype.Timestamptz `json:"verified_at"`
	VerificationToken   pgtype.Text        `json:"verification_token"`
	ResetToken          pgtype.Text        `json:"reset_token"`
	ResetTokenExpiresAt pgtype.Timestamptz `json:"reset_token_expires_at"`
}
