// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_members.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrganizationMember = `-- name: AddOrganizationMember :one
INSERT INTO organization_members (
  organization_id,
  user_id,
  role
) VALUES (
  $1, $2, $3
)
RETURNING id, organization_id, user_id, role, created_at
`

type AddOrganizationMemberParams struct {
	OrganizationID pgtype.UUID      `json:"organization_id"`
	UserID         pgtype.UUID      `json:"user_id"`
	Role           OrganizationRole `json:"role"`
}

func (q *Queries) AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, addOrganizationMember, arg.OrganizationID, arg.UserID, arg.Role)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationMember = `-- name: GetOrganizationMember :one
SELECT id, organization_id, user_id, role, created_at FROM organization_members
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrganizationMember(ctx context.Context, id pgtype.UUID) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMember, id)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationMemberByUserAndOrg = `-- name: GetOrganizationMemberByUserAndOrg :one
SELECT id, organization_id, user_id, role, created_at FROM organization_members
WHERE organization_id = $1 AND user_id = $2 LIMIT 1
`

type GetOrganizationMemberByUserAndOrgParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetOrganizationMemberByUserAndOrg(ctx context.Context, arg GetOrganizationMemberByUserAndOrgParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMemberByUserAndOrg, arg.OrganizationID, arg.UserID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT id, organization_id, user_id, role, created_at FROM organization_members
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrganizationMembers(ctx context.Context, organizationID pgtype.UUID) ([]OrganizationMember, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationMember{}
	for rows.Next() {
		var i OrganizationMember
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrganizations = `-- name: ListUserOrganizations :many
SELECT id, organization_id, user_id, role, created_at FROM organization_members
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserOrganizations(ctx context.Context, userID pgtype.UUID) ([]OrganizationMember, error) {
	rows, err := q.db.Query(ctx, listUserOrganizations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationMember{}
	for rows.Next() {
		var i OrganizationMember
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOrganizationMember = `-- name: RemoveOrganizationMember :exec
DELETE FROM organization_members
WHERE id = $1
`

func (q *Queries) RemoveOrganizationMember(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeOrganizationMember, id)
	return err
}

const updateOrganizationMemberRole = `-- name: UpdateOrganizationMemberRole :one
UPDATE organization_members
SET role = $2
WHERE id = $1
RETURNING id, organization_id, user_id, role, created_at
`

type UpdateOrganizationMemberRoleParams struct {
	ID   pgtype.UUID      `json:"id"`
	Role OrganizationRole `json:"role"`
}

func (q *Queries) UpdateOrganizationMemberRole(ctx context.Context, arg UpdateOrganizationMemberRoleParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, updateOrganizationMemberRole, arg.ID, arg.Role)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
