// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photos.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO photos (
  inspection_id,
  storage_url,
  thumbnail_url
) VALUES (
  $1, $2, $3
)
RETURNING id, inspection_id, storage_url, created_at, thumbnail_url
`

type CreatePhotoParams struct {
	InspectionID pgtype.UUID `json:"inspection_id"`
	StorageUrl   string      `json:"storage_url"`
	ThumbnailUrl pgtype.Text `json:"thumbnail_url"`
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, createPhoto, arg.InspectionID, arg.StorageUrl, arg.ThumbnailUrl)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.InspectionID,
		&i.StorageUrl,
		&i.CreatedAt,
		&i.ThumbnailUrl,
	)
	return i, err
}

const deletePhoto = `-- name: DeletePhoto :exec
DELETE FROM photos
WHERE id = $1
`

func (q *Queries) DeletePhoto(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePhoto, id)
	return err
}

const getPhoto = `-- name: GetPhoto :one
SELECT id, inspection_id, storage_url, created_at, thumbnail_url FROM photos
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPhoto(ctx context.Context, id pgtype.UUID) (Photo, error) {
	row := q.db.QueryRow(ctx, getPhoto, id)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.InspectionID,
		&i.StorageUrl,
		&i.CreatedAt,
		&i.ThumbnailUrl,
	)
	return i, err
}

const getPhotoCountByOrganizationAndDateRange = `-- name: GetPhotoCountByOrganizationAndDateRange :one
SELECT COUNT(*) as count
FROM photos ph
JOIN inspections i ON i.id = ph.inspection_id
JOIN projects p ON p.id = i.project_id
WHERE p.organization_id = $1
  AND ph.created_at >= $2
  AND ph.created_at < $3
`

type GetPhotoCountByOrganizationAndDateRangeParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2    pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) GetPhotoCountByOrganizationAndDateRange(ctx context.Context, arg GetPhotoCountByOrganizationAndDateRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, getPhotoCountByOrganizationAndDateRange, arg.OrganizationID, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listPhotos = `-- name: ListPhotos :many
SELECT id, inspection_id, storage_url, created_at, thumbnail_url FROM photos
WHERE inspection_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPhotos(ctx context.Context, inspectionID pgtype.UUID) ([]Photo, error) {
	rows, err := q.db.Query(ctx, listPhotos, inspectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.InspectionID,
			&i.StorageUrl,
			&i.CreatedAt,
			&i.ThumbnailUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
