// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photos.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO photos (
  inspection_id,
  storage_url
) VALUES (
  $1, $2
)
RETURNING id, inspection_id, storage_url, created_at
`

type CreatePhotoParams struct {
	InspectionID pgtype.UUID `json:"inspection_id"`
	StorageUrl   string      `json:"storage_url"`
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, createPhoto, arg.InspectionID, arg.StorageUrl)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.InspectionID,
		&i.StorageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deletePhoto = `-- name: DeletePhoto :exec
DELETE FROM photos
WHERE id = $1
`

func (q *Queries) DeletePhoto(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePhoto, id)
	return err
}

const getPhoto = `-- name: GetPhoto :one
SELECT id, inspection_id, storage_url, created_at FROM photos
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPhoto(ctx context.Context, id pgtype.UUID) (Photo, error) {
	row := q.db.QueryRow(ctx, getPhoto, id)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.InspectionID,
		&i.StorageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listPhotos = `-- name: ListPhotos :many
SELECT id, inspection_id, storage_url, created_at FROM photos
WHERE inspection_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPhotos(ctx context.Context, inspectionID pgtype.UUID) ([]Photo, error) {
	rows, err := q.db.Query(ctx, listPhotos, inspectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.InspectionID,
			&i.StorageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
