// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
  organization_id,
  name,
  description,
  project_type,
  address,
  city,
  state,
  zip_code,
  country
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, organization_id, name, created_at, updated_at, description, project_type, status, address, city, state, zip_code, country
`

type CreateProjectParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	ProjectType    pgtype.Text `json:"project_type"`
	Address        pgtype.Text `json:"address"`
	City           pgtype.Text `json:"city"`
	State          pgtype.Text `json:"state"`
	ZipCode        pgtype.Text `json:"zip_code"`
	Country        pgtype.Text `json:"country"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.ProjectType,
		arg.Address,
		arg.City,
		arg.State,
		arg.ZipCode,
		arg.Country,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.ProjectType,
		&i.Status,
		&i.Address,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Country,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, organization_id, name, created_at, updated_at, description, project_type, status, address, city, state, zip_code, country FROM projects
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.ProjectType,
		&i.Status,
		&i.Address,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Country,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, organization_id, name, created_at, updated_at, description, project_type, status, address, city, state, zip_code, country FROM projects
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context, organizationID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.ProjectType,
			&i.Status,
			&i.Address,
			&i.City,
			&i.State,
			&i.ZipCode,
			&i.Country,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
  name = COALESCE($1, name),
  description = COALESCE($2, description),
  project_type = COALESCE($3, project_type),
  status = COALESCE($4, status),
  address = COALESCE($5, address),
  city = COALESCE($6, city),
  state = COALESCE($7, state),
  zip_code = COALESCE($8, zip_code),
  country = COALESCE($9, country),
  updated_at = CURRENT_TIMESTAMP
WHERE id = $10
RETURNING id, organization_id, name, created_at, updated_at, description, project_type, status, address, city, state, zip_code, country
`

type UpdateProjectParams struct {
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	ProjectType pgtype.Text `json:"project_type"`
	Status      pgtype.Text `json:"status"`
	Address     pgtype.Text `json:"address"`
	City        pgtype.Text `json:"city"`
	State       pgtype.Text `json:"state"`
	ZipCode     pgtype.Text `json:"zip_code"`
	Country     pgtype.Text `json:"country"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.ProjectType,
		arg.Status,
		arg.Address,
		arg.City,
		arg.State,
		arg.ZipCode,
		arg.Country,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.ProjectType,
		&i.Status,
		&i.Address,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Country,
	)
	return i, err
}
