// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
  inspection_id,
  storage_url
) VALUES (
  $1, $2
)
RETURNING id, inspection_id, storage_url, created_at
`

type CreateReportParams struct {
	InspectionID pgtype.UUID `json:"inspection_id"`
	StorageUrl   string      `json:"storage_url"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport, arg.InspectionID, arg.StorageUrl)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.InspectionID,
		&i.StorageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReport = `-- name: DeleteReport :exec
DELETE FROM reports
WHERE id = $1
`

func (q *Queries) DeleteReport(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReport, id)
	return err
}

const getReport = `-- name: GetReport :one
SELECT id, inspection_id, storage_url, created_at FROM reports
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetReport(ctx context.Context, id pgtype.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReport, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.InspectionID,
		&i.StorageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listReports = `-- name: ListReports :many
SELECT id, inspection_id, storage_url, created_at FROM reports
WHERE inspection_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReports(ctx context.Context, inspectionID pgtype.UUID) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReports, inspectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.InspectionID,
			&i.StorageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
