// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: safety_codes.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSafetyCode = `-- name: CreateSafetyCode :one
INSERT INTO safety_codes (
  code,
  description,
  country,
  state_province
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, code, description, country, state_province, created_at, updated_at
`

type CreateSafetyCodeParams struct {
	Code          string      `json:"code"`
	Description   string      `json:"description"`
	Country       pgtype.Text `json:"country"`
	StateProvince pgtype.Text `json:"state_province"`
}

func (q *Queries) CreateSafetyCode(ctx context.Context, arg CreateSafetyCodeParams) (SafetyCode, error) {
	row := q.db.QueryRow(ctx, createSafetyCode,
		arg.Code,
		arg.Description,
		arg.Country,
		arg.StateProvince,
	)
	var i SafetyCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Country,
		&i.StateProvince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSafetyCode = `-- name: DeleteSafetyCode :exec
DELETE FROM safety_codes
WHERE id = $1
`

func (q *Queries) DeleteSafetyCode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSafetyCode, id)
	return err
}

const getSafetyCode = `-- name: GetSafetyCode :one
SELECT id, code, description, country, state_province, created_at, updated_at FROM safety_codes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSafetyCode(ctx context.Context, id pgtype.UUID) (SafetyCode, error) {
	row := q.db.QueryRow(ctx, getSafetyCode, id)
	var i SafetyCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Country,
		&i.StateProvince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSafetyCodeByCode = `-- name: GetSafetyCodeByCode :one
SELECT id, code, description, country, state_province, created_at, updated_at FROM safety_codes
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetSafetyCodeByCode(ctx context.Context, code string) (SafetyCode, error) {
	row := q.db.QueryRow(ctx, getSafetyCodeByCode, code)
	var i SafetyCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Country,
		&i.StateProvince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSafetyCodes = `-- name: ListSafetyCodes :many
SELECT id, code, description, country, state_province, created_at, updated_at FROM safety_codes
ORDER BY code
`

func (q *Queries) ListSafetyCodes(ctx context.Context) ([]SafetyCode, error) {
	rows, err := q.db.Query(ctx, listSafetyCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SafetyCode{}
	for rows.Next() {
		var i SafetyCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Country,
			&i.StateProvince,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSafetyCodesByCountry = `-- name: ListSafetyCodesByCountry :many
SELECT id, code, description, country, state_province, created_at, updated_at FROM safety_codes
WHERE country = $1
ORDER BY code
`

func (q *Queries) ListSafetyCodesByCountry(ctx context.Context, country pgtype.Text) ([]SafetyCode, error) {
	rows, err := q.db.Query(ctx, listSafetyCodesByCountry, country)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SafetyCode{}
	for rows.Next() {
		var i SafetyCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Country,
			&i.StateProvince,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSafetyCodesByStateProvince = `-- name: ListSafetyCodesByStateProvince :many
SELECT id, code, description, country, state_province, created_at, updated_at FROM safety_codes
WHERE state_province = $1
ORDER BY code
`

func (q *Queries) ListSafetyCodesByStateProvince(ctx context.Context, stateProvince pgtype.Text) ([]SafetyCode, error) {
	rows, err := q.db.Query(ctx, listSafetyCodesByStateProvince, stateProvince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SafetyCode{}
	for rows.Next() {
		var i SafetyCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Country,
			&i.StateProvince,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSafetyCode = `-- name: UpdateSafetyCode :one
UPDATE safety_codes
SET
  code = COALESCE($2, code),
  description = COALESCE($3, description),
  country = COALESCE($4, country),
  state_province = COALESCE($5, state_province),
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, code, description, country, state_province, created_at, updated_at
`

type UpdateSafetyCodeParams struct {
	ID            pgtype.UUID `json:"id"`
	Code          string      `json:"code"`
	Description   string      `json:"description"`
	Country       pgtype.Text `json:"country"`
	StateProvince pgtype.Text `json:"state_province"`
}

func (q *Queries) UpdateSafetyCode(ctx context.Context, arg UpdateSafetyCodeParams) (SafetyCode, error) {
	row := q.db.QueryRow(ctx, updateSafetyCode,
		arg.ID,
		arg.Code,
		arg.Description,
		arg.Country,
		arg.StateProvince,
	)
	var i SafetyCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Country,
		&i.StateProvince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
