// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email,
  username,
  password_hash,
  first_name,
  last_name
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, email, username, password_hash, first_name, last_name, status, status_reason, created_at, updated_at, last_login_at, verified_at, verification_token, reset_token, reset_token_expires_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	FirstName    pgtype.Text `json:"first_name"`
	LastName     pgtype.Text `json:"last_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.StatusReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.VerifiedAt,
		&i.VerificationToken,
		&i.ResetToken,
		&i.ResetTokenExpiresAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email, username, password_hash, first_name, last_name, status, status_reason, created_at, updated_at, last_login_at, verified_at, verification_token, reset_token, reset_token_expires_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.StatusReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.VerifiedAt,
		&i.VerificationToken,
		&i.ResetToken,
		&i.ResetTokenExpiresAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, first_name, last_name, status, status_reason, created_at, updated_at, last_login_at, verified_at, verification_token, reset_token, reset_token_expires_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.StatusReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.VerifiedAt,
		&i.VerificationToken,
		&i.ResetToken,
		&i.ResetTokenExpiresAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password_hash, first_name, last_name, status, status_reason, created_at, updated_at, last_login_at, verified_at, verification_token, reset_token, reset_token_expires_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.StatusReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.VerifiedAt,
		&i.VerificationToken,
		&i.ResetToken,
		&i.ResetTokenExpiresAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, username, password_hash, first_name, last_name, status, status_reason, created_at, updated_at, last_login_at, verified_at, verification_token, reset_token, reset_token_expires_at FROM users
WHERE status = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context, status UserStatus) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Status,
			&i.StatusReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.VerifiedAt,
			&i.VerificationToken,
			&i.ResetToken,
			&i.ResetTokenExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  first_name = COALESCE($2, first_name),
  last_name = COALESCE($3, last_name),
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, email, username, password_hash, first_name, last_name, status, status_reason, created_at, updated_at, last_login_at, verified_at, verification_token, reset_token, reset_token_expires_at
`

type UpdateUserParams struct {
	ID        pgtype.UUID `json:"id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.FirstName, arg.LastName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.StatusReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.VerifiedAt,
		&i.VerificationToken,
		&i.ResetToken,
		&i.ResetTokenExpiresAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET
  status = $2,
  status_reason = $3,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, email, username, password_hash, first_name, last_name, status, status_reason, created_at, updated_at, last_login_at, verified_at, verification_token, reset_token, reset_token_expires_at
`

type UpdateUserStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	Status       UserStatus  `json:"status"`
	StatusReason pgtype.Text `json:"status_reason"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status, arg.StatusReason)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.StatusReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.VerifiedAt,
		&i.VerificationToken,
		&i.ResetToken,
		&i.ResetTokenExpiresAt,
	)
	return i, err
}
